export const ALL_COFFEES_REQUEST = 'ALL_COFFEES_REQUEST';
export const ALL_COFFEES_SUCCESS = 'ALL_COFFEES_SUCCESS';
export const ALL_COFFEES_FAIL = 'ALL_COFFEES_FAIL';

export const COFFEE_DETAILS_REQUEST = 'COFFEE_DETAILS_REQUEST';
export const COFFEE_DETAILS_SUCCESS = 'COFFEE_DETAILS_SUCCESS';
export const COFFEE_DETAILS_FAIL = 'COFFEE_DETAILS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';