export const ALL_COFFEES_REQUEST = 'ALL_COFFEES_REQUEST';
export const ALL_COFFEES_SUCCESS = 'ALL_COFFEES_SUCCESS';
export const ALL_COFFEES_FAIL = 'ALL_COFFEES_FAIL';

export const COFFEE_DETAILS_REQUEST = 'COFFEE_DETAILS_REQUEST';
export const COFFEE_DETAILS_SUCCESS = 'COFFEE_DETAILS_SUCCESS';
export const COFFEE_DETAILS_FAIL = 'COFFEE_DETAILS_FAIL';

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

export const ADMIN_COFFEES_REQUEST = 'ADMIN_COFFEES_REQUEST'
export const ADMIN_COFFEES_SUCCESS = 'ADMIN_COFFEES_SUCCESS'
export const ADMIN_COFFEES_FAIL = 'ADMIN_COFFEES_FAIL'

export const NEW_COFFEE_REQUEST = 'NEW_COFFEE_REQUEST'
export const NEW_COFFEE_SUCCESS = 'NEW_COFFEE_SUCCESS'
export const NEW_COFFEE_RESET = 'NEW_COFFEE_RESET'
export const NEW_COFFEE_FAIL = 'NEW_COFFEE_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS';