export const ALL_COFFEES_REQUEST = 'ALL_COFFEES_REQUEST';
export const ALL_COFFEES_SUCCESS = 'ALL_COFFEES_SUCCESS';
export const ALL_COFFEES_FAIL = 'ALL_COFFEES_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';